Py_Practica/routes/route_generador.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
import requests

route_generador = Blueprint('route_generador', __name__)

BASE_URL = "http://localhost:8088/myapp/generador"


@route_generador.route('/')
def home():
    try:
        r = requests.get(f"{BASE_URL}/list")
        r.raise_for_status()
        data = r.json()
        return render_template('/generadores/generador.html', lista=data["data"])
    except requests.exceptions.RequestException as e:
        return f"Error al obtener la lista de generadores: {str(e)}", 500


@route_generador.route('/agregar')
def agregar_generador():
    return render_template('/generadores/agregar_generador.html')


@route_generador.route('/save', methods=['POST'])
def save_generador():
    try:
        form_data = request.form.to_dict()
        r = requests.post(f"{BASE_URL}/save", json=form_data)
        r.raise_for_status()
        return redirect(url_for('route_generador.home'))
    except requests.exceptions.RequestException as e:
        flash(f"Error al guardar el generador: {str(e)}", "error")
        return redirect(url_for('route_generador.agregar_generador'))


@route_generador.route('/<int:id>/modificar')
def get_generador_by_id(id):
    try:
        r = requests.get(f"{BASE_URL}/{id}")
        r.raise_for_status()
        data = r.json()
        return render_template('/generadores/modificar_generador.html', generador=data["data"])
    except requests.exceptions.RequestException as e:
        return f"Error al obtener el generador: {str(e)}", 500


@route_generador.route('/<int:id>/update', methods=['POST'])
def update_generador(id):
    if request.form.get("_method") == "PUT":
        try:
            data = {
                "nombre": requests.form.get("nombre"),
                "precio": request.form.get("precio"),
                "consumoPorHora": request.form.get("consumoPorHora"),
                "energiaGenerada": request.form.get("energiaGenerada"),
                "uso": request.form.get("uso")
            }
            r = requests.put(f"{BASE_URL}/{id}/update", json=data)
            r.raise_for_status()
            return redirect(url_for('route_generador.home'))
        except requests.exceptions.RequestException as e:
            print(f"[ERROR] Falló el PUT: {str(e)}")
            flash(f"Error al actualizar el generador: {str(e)}", "error")
            return redirect(url_for('route_generador.home'))
    else:
        flash("Método no permitido", "error")
        return redirect(url_for('route_generador.home'))
    
    

@route_generador.route('/<id>/eliminar', methods=['POST'])
def eliminar_generador(id):
    try:
        r = requests.delete(f"{BASE_URL}/{id}/delete")
        r.raise_for_status()
        data = r.json()
        return redirect(url_for('route_generador.home'))
    except requests.exceptions.RequestException as e:
        return f"Error al obtener el generador: {str(e)}", 500


@route_generador.route('list/ordenar/<attribute>/<type>/<metodo>', methods=['GET'])
def metodosOrdenacion(attribute, type, metodo):
    try: 
        r = requests.get(f"{BASE_URL}/list/order/{attribute}/{type}/{metodo}");
        r.raise_for_status()
        data = r.json()  
        return render_template('/generadores/generador.html', lista=data["data"])
    except requests.exceptions.RequestException as e:
        flash(f"Error al obtener las familias: {str(e)}", "error")
        return render_template('/generadores/generador.html', lista=[])

@route_generador.route('/list/search/<attribute>/<value>', methods=['GET'])
def search_criteria(attribute, value):
    try:
        r = requests.get(f'{BASE_URL}/list/search/{attribute}/{value}')
        r.raise_for_status()
        response = r.json()  
        
        if response.get("status") == "ERROR":
            print(f"Error desde la API: {response.get('msg', 'Error desconocido')}")
            return render_template('/generadores/generador.html', lista=[], error=response.get('msg'))
        
        data = response.get("data", [])
        
        if not isinstance(data, list):
            data = [data]
        
        return render_template('/generadores/generador.html', lista=data,)
    
    except requests.RequestException as e:
        print(f"Error al conectar con la API: {e}")
        return render_template('/generadores/generador.html', lista=[], error="Error")
    

Py_Practica/templates/generadores/agregar_generador.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Agregar Generador</title>
    <link href="/static/image/gen.png" rel="icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='agregar_generador.css') }}">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mt-4">Agregar Nuevo Generador <i class="fas fa-plus-circle"></i></h1>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="alert alert-danger" role="alert">
                    {% for category, message in messages %}
                        <div>{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}

        <form method="post" action="{{ url_for('route_generador.save_generador') }}">
            <div class="form-group">
                <label for="precio">Precio <i class="fas fa-dollar-sign"></i>:</label>
                <input type="number" class="form-control" id="precio" name="precio" step="0.01" required aria-label="Precio del generador">
            </div>
            <div class="form-group">
                <label for="consumoPorHora">Consumo por Hora <i class="fas fa-bolt"></i>:</label>
                <input type="number" class="form-control" id="consumoPorHora" name="consumoPorHora" step="0.01" required aria-label="Consumo por hora del generador">
            </div>
            <div class="form-group">
                <label for="energiaGenerada">Energía Generada <i class="fas fa-solar-panel"></i>:</label>
                <input type="number" class="form-control" id="energiaGenerada" name="energiaGenerada" step="0.01" required aria-label="Energía generada por el generador">
            </div>
            <div class="form-group">
                <label for="uso">Uso del Generador <i class="fas fa-tools"></i>:</label>
                <input type="text" class="form-control" id="uso" name="uso" aria-label="Uso del generador">
            </div>

            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Agregar</button>
            <a href="{{ url_for('route_generador.home') }}" class="btn btn-secondary"><i class="fas fa-times"></i> Cancelar</a>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Py_Practica/templates/generadores/eliminar_generador.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Eliminar Generador</title>
    <link href="/static/image/gen.png" rel="icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-4">Eliminar Generador</h1>

        <p>¿Estás seguro de que deseas eliminar el generador con ID {{ generador.id }}?</p>
        <ul>
            <li><strong>Precio:</strong> {{ generador.precio }}</li>
            <li><strong>Consumo por Hora:</strong> {{ generador.consumoPorHora }}</li>
            <li><strong>Energía Generada:</strong> {{ generador.energiaGenerada }}</li>
            <li><strong>Uso:</strong> {{ generador.uso }}</li>
        </ul>

        <!-- URL dinámico y método POST -->
        <form method="post" action="{{ url_for('route_generador.delete_generador', id=generador.id) }}" onsubmit="return confirm('¿Seguro que deseas eliminar este generador?');">
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a href="{{ url_for('route_generador.home') }}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Py_Practica/templates/generadores/generador.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Listado de Generadores</title>
    <link href="/static/image/gen.png" rel="icon">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet"> <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ url_for('static', filename='generador.css') }}"> <!-- Enlace al archivo CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            function url_change() {
                var url = "http://127.0.0.1:5000/generador/list/search";
                var busqueda = $("#busqueda").val();
                var atributo = $("#atributo").val();
                var new_url = url + "/" + atributo + "/" + busqueda;
                $("#boton").attr("href", new_url);
            }
        
            $("#busqueda").keyup(function () {
                url_change();
            });
            $("#atributo").change(function () {
                url_change();
            });
        
            function updateArrowUrls() {
                var method = $("#ordenar").val(); 
            
                $("a.text-primary").each(function () {
                    var baseUrl = $(this).data("original-href"); 
                    $(this).attr("href", baseUrl + method);
                });
            }
            
            $("a.text-primary").each(function () {
                if (!$(this).data("original-href")) {
                    $(this).data("original-href", $(this).attr("href")); 
                }
            });
            
            $("#ordenar").change(function () {
                updateArrowUrls();
            });
            
            updateArrowUrls();
            });
    </script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <a class="navbar-brand" href="{{ url_for('inicio') }}">Familias y generadores</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/familia"><i class="fas fa-users"></i> Familia</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/generador"><i class="fas fa-plug"></i> Generador</a>
                </li>
            </ul>
        </div>
    </nav>
    

    <div class="container mt-5">
        <h1 class="mb-4 text-electricity">Listado de Generadores</h1>
        
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="alert alert-warning" role="alert">
                    <i class="fas fa-exclamation-circle"></i> {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}

        <div class="mb-3">
            <a href="{{ url_for('route_generador.agregar_generador') }}" class="btn btn-success">
                <i class="fas fa-plus-circle"></i> Agregar Generador
            </a>
        </div>

        <div class="d-flex align-items-center">
            <label for="atributo" class="mr-2">Atributo:</label>
            <select id="atributo" class="form-select w-auto mr-2">
                    <option value="nombre">Marca</option>
                    <option value="precio">Precio</option>
                    <option value="consumoPorHora">Consumo por hora</option>
                    <option value="energiaGenerada">Energia generada</option>
                    <option value="uso">Uso</option>
            </select>
        </div>
        <div class="d-flex align-items-center mr-2">
            <input type="text" id="busqueda" class="form-control" placeholder="Buscar en generadores">
        </div>
        <div class="d-flex align-items-center">
            <a id="boton" class="btn btn-primary">
                <i class="fas fa-search"></i>
            </a>
            <a href="/generador" class="btn btn-danger">Regresar</a>
        </div>
        <div class="d-flex align-items-center gap-2">
            <label for="ordenar" class="mr-2">Elige un metodo</label>
            <select id="ordenar" class="form-select w-auto">
                <option value="shell">Metodo Shell</option>
                <option value="merge">Metodo Merge</option>
                <option value="quick">Metodo Quick</option>
            </select>
        </div>

        {% if lista and lista|length > 0 %}
            <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered animate__animated animate__fadeIn">
                    <thead class="thead-dark">
                        <tr>

                            <th class="text-center" style="max-width: 125px; font-size: 0.9em;">
                                <div>
                                    <i class="fas fa-cogs"></i> marca
                                </div>
                                <div>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='nombre', type=1, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-up"></i>
                                    </a>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='nombre', type=0, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-down"></i>
                                    </a>
                                </div>
                            </th>


                            <th class="text-center" style="max-width: 125px; font-size: 0.9em;">
                                <div>
                                    <i class="fas fa-money-bill-wave"></i> Precio
                                </div>
                                <div>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='precio', type=1, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-up"></i>
                                    </a>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='precio', type=0, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-down"></i>
                                    </a>
                                </div>
                            </th>

                            <th class="text-center" style="max-width: 125px; font-size: 0.9em;">
                                <div>
                                    <i class="fas fa-gas-pump"></i> Consumo por hora
                                </div>
                                <div>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='consumoPorHora', type=1, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-up"></i>
                                    </a>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='consumoPorHora', type=0, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-down"></i>
                                    </a>
                                </div>
                            </th>

                            <th class="text-center" style="max-width: 125px; font-size: 0.9em;">
                                <div>
                                    <i class="fas fa-bolt"></i> Energia generada
                                </div>
                                <div>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='energiaGenerada', type=1, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-up"></i>
                                    </a>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='energiaGenerada', type=0, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-down"></i>
                                    </a>
                                </div>
                            </th>

                            <th class="text-center" style="max-width: 125px; font-size: 0.9em;">
                                <div>
                                    <i class="fas fa-cogs"></i> Uso
                                </div>
                                <div>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='uso', type=1, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-up"></i>
                                    </a>
                                    <a href="{{ url_for('route_generador.metodosOrdenacion', attribute='uso', type=0, metodo='') }}" class="text-primary mx-1">
                                        <i class="fas fa-arrow-down"></i>
                                    </a>
                                </div>
                            </th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in lista %}
                        <tr>
                            
                            <td>{{ item.nombre }}</td>
                            <td>{{ item.precio }}</td>
                            <td>{{ item.consumoPorHora }}</td>
                            <td>{{ item.energiaGenerada }}</td>
                            <td>{{ item.uso or "No especificado" }}</td>
                            <td>
                                <a href="{{ url_for('route_generador.get_generador_by_id', id=item.id) }}" class="btn btn-primary btn-sm">
                                    <i class="fas fa-edit"></i> Modificar
                                </a>
                                <form action="{{ url_for('route_generador.eliminar_generador', id=item.id) }}" method="POST" style="display:inline;">
                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de eliminar este generador?');">
                                        <i class="fas fa-trash-alt"></i> Eliminar
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p class="text-muted">No hay generadores registrados en el sistema.</p>
        {% endif %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Py_Practica/templates/generadores/modificar_generador.html
<!DOCTYPE html>
<html>
<head>
    <title>Modificar Generador</title>
    <link href="/static/image/gen.png" rel="icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-4">Modificar Generador</h1>

        <form method="POST" action="/generador/{{ generador.id }}/update">
            <div class="form-group">
                <input type="hidden" name = "_method" value="PUT">
                <label for="precio">Precio:</label>
                <input type="number" class="form-control" id="precio" name="precio" value="{{ generador.precio }}" step="0.01" required>
            </div>
            <div class="form-group">
                <label for="consumoPorHora">Consumo por Hora:</label>
                <input type="number" class="form-control" id="consumoPorHora" name="consumoPorHora" value="{{ generador.consumoPorHora }}" step="0.01" required>
            </div>
            <div class="form-group">
                <label for="energiaGenerada">Energía Generada:</label>
                <input type="number" class="form-control" id="energiaGenerada" name="energiaGenerada" value="{{ generador.energiaGenerada }}" step="0.01" required>
            </div>
            <div class="form-group">
                <label for="uso">Uso del Generador:</label>
                <input type="text" class="form-control" id="uso" name="uso" value="{{ generador.uso }}">
            </div>
            
            <button type="submit" class="btn btn-primary">Actualizar</button>
            <a href="/generador" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
</body>
</html>